### ISSUE TITLE
View Inventory Throws An Error

### ISSUE THREAD

**Issue by PolyframeX** [RazorPlay01/InvView_Forge#1]
When viewing anybodys inventory when they leave the game and aren't present.

https://pastebin.com/eiwYquqt

**Comment by RazorPlay01** [comment]
Could you explain to me well how to recreate it. I have tried several things and I have not been able to get the error you mention.

**Comment by PoIyframeX** [comment]
All I did was /view inv. So I suppose its a mod incompatibility then.

**Comment by RazorPlay01** [comment]
If you discover which mod causes this incompatibility, I would appreciate it if you would notify me to see if it is possible to solve said error.

**Comment by HabloHobbies2007** [comment]
Hello, testing this on my server, this issue appeared after I added the 1.20.1 Forge version of Luckperms.

**Comment by RazorPlay01** [comment]
interesting is because luckperms implements its own permissions system and I don't have that in mind for the mod and I use the vanilla system.
