### ISSUE TITLE
[BUG] If you SHIFT-click on an item in the inventory view, the item will disappear. Forge 1.19.2

### ISSUE THREAD

**Issue by kitovoi111** [RazorPlay01/InvView_Forge#6]
Forge 1.19.2
I opened the player's inventory /view {player} inv and wanted to drag the item using SHIFT but the item disappeared

**Comment by RazorPlay01** [comment]
It should be fixed in the version just released.

**Comment by Alerymin** [comment]
got this bug a few minutes ago

NeoForge 1.21.1

**Comment by RazorPlay01** [comment]
This problem is solved in newer versions of the mod, when I have some time I will do the backport
